name: Create Release
on:
  create

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        if: contains(github.ref, '/release-')
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release < MAJOR.MINOR.PATCH >
          body: |
            PR: #PR
          draft: true
          prerelease: false
