name: Create Release
on:
  create

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        if: contains(github.ref, '/release-')
        uses: mrexox/release-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_branch: ${{ github.ref }}
          draft: true
          prerelease: true
