name: Automated release management
on:
  push:
    branches:
      - release-*

jobs:
  build:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release or bump a version
        uses: invisionapp/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.ACTION_TOKEN }}
          pal-repo-name: meekly/release-action@v1.0.0
          release_branch: ${{ github.ref }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
