name: Merge master to develop
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Pull Request
    runs-on: ubuntu-18.04
    steps:
      - name: Create Pull Request
        uses: Logerfo/gitflow-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dev: develop
          master: master
          auto-merge: false
          require-merge: false
          label: MASTER_TO_DEVELOP
