name: Merge master to develop
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Pull Request
    runs-on: ubuntu-18.04
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
